name: CI-CD
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # checkout in to the current repo to pull the code
      - uses: actions/checkout@v3  
      # Specifying a certain node version
      - name: NodeJS Setup
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.0'
      # Install dependencies
      - run: npm ci
      # Check code formatting
      - run: npm run lint:check
      # Run automated tests
      - run: npm run test -- --coverage
        env:
          CI: true
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        run: echo "I'm gonna publish after test job"